# Generated by Django 4.2 on 2025-04-14 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_orderitem_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
    ]
